### PR TITLE
Clear artwork

### PR DESCRIPTION
**Pull request by duncanbeevers**

### CODE REVIEW

**Comment by elan** [comment]
Super cool, thanks!

**Comment by elan** [comment]
Actually, I _think_ we need to only do that once, since calling `simplify.setCurrentArtwork(null);` every time will cause flashing, IIRC?

**Comment by duncanbeevers** [comment]
I haven't actually tried this out. According to their docs, setting the artwork to `null` instructs Simplify to try and go out and find its own artwork.

**Comment by elan** [comment]
Yep, I've tried that before and it sort of worked, but we only want to do it once per track.

**Pull request merged**
